- id: "a5b6b05f-4806-4ec9-b4f3-eccdc50c9c6c"
  alias: "Añadir productos faltantes a la lista"
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: grocy.add_missing_products_to_shopping_list
