---
default_config:

homeassistant:
  name: "Inventario IA"
  currency: "EUR"
  country: "ES"
  unit_system: metric

# Integración Grocy (requiere haberla instalado desde HACS)
grocy:
  url: "http://grocy:9283"
  api_key: !secret grocy_api_key
  verify_ssl: false

input_number:
  grocy_amount:
    name: Grocy amount
    min: 1
    max: 20
    step: 1

input_text:
  grocy_product_id:
    name: Grocy product ID
    max: 6
  grocy_chore_id:
    name: Grocy chore ID
    max: 6

frontend:
  themes: !include themes.yaml
