---
default_config:

homeassistant:
  name: "Inventario IA"
  currency: "EUR"
  country: "ES"
  unit_system: metric

# Integración Grocy (requiere haberla instalado desde HACS)
grocy:
  url: "http://grocy:9283"
  api_key: !secret grocy_api_key
  verify_ssl: false
