---
"Grocy Compact":
  primary-color: "#1e88e5"
  accent-color: "#ffb300"
  primary-text-color: "#e0e0e0"
  secondary-text-color: "#bdbdbd"
  card-background-color: "#2b2c2e"
  primary-background-color: "#1e1e1e"
  secondary-background-color: "#2a2a2a"
  app-header-background-color: "#1b1b1b"
  state-icon-color: "#e0e0e0"
  paper-item-icon-color: "#e0e0e0"
  ha-card-border-radius: "4px"
  ha-card-box-shadow: "none"
  masonry-view-card-margin: "4px"
