---
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=${TZ}
    volumes:
      - ./homeassistant/config:/config
    ports:
      - "8123:8123"
    restart: unless-stopped
    networks:
      - ha_net

  grocy:
    container_name: grocy
    image: lscr.io/linuxserver/grocy:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./grocy/config:/config
    ports:
      - "9283:9283"
    restart: unless-stopped
    networks:
      - ha_net

  barcodebuddy:
    container_name: barcodebuddy
    image: f0rc3/barcodebuddy-docker:latest
    environment:
      OVERRIDDEN_USER_CONFIG: "GROCY_API_URL=${GROCY_INTERNAL_URL};GROCY_API_KEY=${GROCY_API_KEY}"  # yamllint disable-line rule:line-length
    volumes:
      - bb_config:/config
    ports:
      - "${BB_HTTP_PORT}:80"
    restart: unless-stopped
    networks:
      - ha_net

networks:
  ha_net:
    driver: bridge

volumes:
  bb_config:
